plugins:
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'bin/*'
    - 'vendor/**/*'
    - 'spec/*_helper.rb'

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: either_consistent

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# To be enforced with Ruby 3.4, so we don't care about it.
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/EmptyElse:
  AllowComments: true

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyleForEmptyBraces: space

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Rails/HasAndBelongsToMany:
  Enabled: false

# My code's too broken to care.
Metrics/AbcSize:
  Enabled: false

# Ditto
Metrics/MethodLength:
  Enabled: false

# ...
Metrics/BlockLength:
  Enabled: false

# ...
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

FactoryBot/SyntaxMethods:
  Enabled: false

# lol. lmao even.
Style/Documentation:
  Enabled: false

# One day.
Rails/I18nLocaleTexts:
  Enabled: false