name: "Branch Push"

on:
  push:
    branches: [ "main" ]

jobs:
  rails:
    uses: ./.github/workflows/component.rails.yml
    secrets: inherit
    permissions:
      contents: read
      checks: write
      pull-requests: write

  brakeman:
    uses: ./.github/workflows/component.brakeman.yml
    permissions:
      contents: read
      security-events: write

  codeql:
    uses: ./.github/workflows/component.codeql.yml
    permissions:
      contents: read
      security-events: write
      packages: read
      actions: read

  deploy:
    if: ${{ !contains(github.event.head_commit.message, '#no-deploy') }}
    uses: ./.github/workflows/component.railway_deploy.yml
    needs: [rails, brakeman, codeql]
    permissions:
      contents: read
      deployments: write