name: Railway Deploy
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # from GitHub config
    steps:
      - uses: actions/checkout@v7

      # Run worker deploy first so we can smoke test.
      - name: Deploy Sidekiq worker
        uses: xivauth/railway-deploy-tool@4686dbccb7a302a3fe3254c65f6f24e966e410e3
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service_id: ${{ secrets.RAILWAY_WORKER_SERVICE_ID }}

      - name: Deploy web nodes
        uses: xivauth/railway-deploy-tool@4686dbccb7a302a3fe3254c65f6f24e966e410e3
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service_id: ${{ secrets.RAILWAY_WEB_SERVICE_ID }}

      # - name: Run DB migrations
      #   run: railway ssh --service=${{ env.WORKER_SVC_ID }} -- rails db:migrate
