name: Railway Deploy
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # Run worker deploy first so we can smoke test.
      - name: Deploy Sidekiq worker
        uses: xivauth/railway-deploy-tool@f7a7fa9eae218f3193f58f8b29a41b75e131c44f
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          environment_id: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          service_id: ${{ secrets.RAILWAY_WORKER_SERVICE_ID }}

      - name: Deploy web nodes
        uses: xivauth/railway-deploy-tool@f7a7fa9eae218f3193f58f8b29a41b75e131c44f
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          environment_id: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          service_id: ${{ secrets.RAILWAY_WEB_SERVICE_ID }}

      # - name: Run DB migrations
      #   run: railway ssh --service=${{ env.WORKER_SVC_ID }} -- rails db:migrate
